{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-cluster.secretName" . }}
  namespace: {{ include "postgres-cluster.namespace" . }}
  labels:
    {{- include "postgres-cluster.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.credentials.username | b64enc }}
  password: {{ .Values.credentials.password | b64enc }}
{{- end }}
